name: project_Autrooasdc
description: ''
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projectautrooasdc
  parentArtefactID: prophecye2etests
  buildSystem: wheel
  author: null
  createdAt: '2024-11-06 07:14:27'
pipelines:
  pipelines/pipelineTest:
    name: pipelineTest
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-11-06 07:14:27'
    datasets:
      inputs:
      - datasets/newDataset
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/newDataset:
    name: newDataset
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2024-11-06 07:27:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 737
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2024-11-06 07:27:05'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-11-06 07:14:27'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-11-06T07:14:27.892711Z'
  name: plibMaven
  version: 8.4.0
  id: '1762936658'
  createdAt: '2024-11-06T07:14:27.892711Z'
  type: plibMaven
- modifiedAt: '2024-11-06T07:14:27.892711Z'
  name: plibPypi
  version: 1.9.24
  id: '1770391932'
  createdAt: '2024-11-06T07:14:27.892711Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.32
    isDefault: true
    author: null
    createdAt: '2024-11-06 07:14:11'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-11-06 07:14:11'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
